name: CI CD - SAM Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: npm ci --only=production

      - name: Build
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          aws-region: ap-south-1

      # Download global-bundle.pem so it's included in the Lambda package
      - name: Download global-bundle.pem
        run: curl https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem -o src/global-bundle.pem

      - name: Package and deploy with SAM
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          sam package \
            --template-file template.yaml \
            --s3-bucket ${{ secrets.DEPLOY_S3_BUCKET }} \
            --output-template-file packaged.yaml
          
          sam deploy \
            --template-file packaged.yaml \
            --stack-name auth-app-prod-v2 \
            --capabilities CAPABILITY_IAM \
            --region ap-south-1 \
            --parameter-overrides MongoUriParam="${MONGO_URI}"
